[versions]
spring = "5.3.26"
springBoot = "2.7.10"
snakeYaml = "2.0"
thymeleaf = "3.1.1.RELEASE"
thymeleafExtrasTime = "3.0.4.RELEASE"
logbackTest = "1.2.11"
jsonSchemaValidator = "1.0.78"
logbackReport = "1.4.5"
jackson = "2.14.2"
gson = "2.10.1"
slf4j = "1.7.36"
h2 = "2.1.214"
jdbi3 = "3.37.1"

lombok = "1.18.26"
findbugs = "3.0.2"

junit4 = "4.13.2"
jupiter = "5.9.2"
jupiterPlatform = "1.9.2"
mockitoCore = "5.2.0"
cucumber = "7.11.1"
testNg = "7.7.1"

lombokPlugin = "8.0.1"
minifyPlugin = "1.3.2"
gitVersionerPlugin = "1.6.7"
indexScanPlugin = "2.6.0"
owaspPlugin = "8.2.0"

checkstyle = "9.2.1"
jacoco = "0.8.2"

[libraries]
spring-core = { module = "org.springframework:spring-core", version.ref = "spring" }
spring-context = { module = "org.springframework:spring-context", version.ref = "spring" }
spring-test = { module = "org.springframework:spring-test", version.ref = "spring" }

spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "springBoot" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "springBoot" }
snake-yaml = { module = "org.yaml:snakeyaml", version.ref = "snakeYaml" }

thymeleaf = { module = "org.thymeleaf:thymeleaf", version.ref = "thymeleaf" }
thymeleaf-extras-java8time = { module = "org.thymeleaf.extras:thymeleaf-extras-java8time", version.ref = "thymeleafExtrasTime" }

logback-classic-test = { module = "ch.qos.logback:logback-classic", version.ref = "logbackTest" }
logback-core-test = { module = "ch.qos.logback:logback-core", version.ref = "logbackTest" }
logback-classic-report = { module = "ch.qos.logback:logback-classic", version.ref = "logbackReport" }
logback-core-report = { module = "ch.qos.logback:logback-core", version.ref = "logbackReport" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
json-schema-validator = { module = "com.networknt:json-schema-validator", version.ref = "jsonSchemaValidator" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

h2 = { module = "com.h2database:h2", version.ref = "h2" }
jdbi3-sqlobject = { module = "org.jdbi:jdbi3-sqlobject", version.ref = "jdbi3" }

lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
findbugs-jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "findbugs" }

junit = { module = "junit:junit", version.ref = "junit4" }

jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jupiter" }
jupiter-core = { module = "org.junit.jupiter:junit-jupiter", version.ref = "jupiter" }
jupiter-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "jupiter" }
jupiter-platform-testkit = { module = "org.junit.platform:junit-platform-testkit", version.ref = "jupiterPlatform" }
jupiter-platform-reporting = { module = "org.junit.platform:junit-platform-reporting", version.ref = "jupiterPlatform" }

mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }

testng = { module = "org.testng:testng", version.ref = "testNg" }

cucumber-java = { module = "io.cucumber:cucumber-java", version.ref = "cucumber" }
cucumber-junit = { module = "io.cucumber:cucumber-junit", version.ref = "cucumber" }
cucumber-spring = { module = "io.cucumber:cucumber-spring", version.ref = "cucumber" }

[bundles]
spring-test = ["spring-core", "spring-context", "spring-test", "snake-yaml"]
logback-test = ["logback-classic-test", "logback-core-test"]
logback-report = ["logback-classic-report", "logback-core-report"]

[plugins]
lombok = { id = "io.freefair.lombok", version.ref = "lombokPlugin" }
minify = { id = "org.gradlewebtools.minify", version.ref = "minifyPlugin" }
versioner = { id = "io.toolebox.git-versioner", version.ref = "gitVersionerPlugin" }
index-scan = { id = "org.sonatype.gradle.plugins.scan", version.ref = "indexScanPlugin" }
owasp-dependencycheck = { id = "org.owasp.dependencycheck", version.ref = "owaspPlugin" }
