[versions]
spring = "5.3.21"
springBoot = "2.7.1"
logback = "1.2.11"
jsonSchemaValidator = "1.0.71"
gson = "2.9.0"
slf4j = "1.7.36"
h2 = "2.1.214"
jdbi3 = "3.30.0"

lombok = "1.18.24"

junit4 = "4.13.2"
jupiter = "5.8.2"
jupiterPlatform = "1.8.2"
mockitoCore = "4.6.1"
cucumber = "7.4.1"
testNg = "7.6.1"

lombokPlugin = "6.5.0.3"
springBootPlugin = "2.7.2"
minifyPlugin = "1.3.1"
gitVersionerPlugin = "1.6.7"
indexScanPlugin = "2.3.0"
owaspPlugin = "7.1.1"

checkstyle = "9.2.1"
jacoco = "0.8.2"

[libraries]
spring-core = { module = "org.springframework:spring-core", version.ref = "spring" }
spring-context = { module = "org.springframework:spring-context", version.ref = "spring" }
spring-web = { module = "org.springframework:spring-web", version.ref = "spring" }
spring-test = { module = "org.springframework:spring-test", version.ref = "spring" }

spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "springBoot" }
spring-boot-starter-json = { module = "org.springframework.boot:spring-boot-starter-json", version.ref = "springBoot" }
spring-boot-starter-thymeleaf = { module = "org.springframework.boot:spring-boot-starter-thymeleaf", version.ref = "springBoot" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor", version.ref = "springBoot" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "springBoot" }

logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logback-core = { module = "ch.qos.logback:logback-core", version.ref = "logback" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
json-schema-validator = { module = "com.networknt:json-schema-validator", version.ref = "jsonSchemaValidator" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

h2 = { module = "com.h2database:h2", version.ref = "h2" }
jdbi3-sqlobject = { module = "org.jdbi:jdbi3-sqlobject", version.ref = "jdbi3" }

lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

junit = { module = "junit:junit", version.ref = "junit4" }

jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jupiter" }
jupiter-core = { module = "org.junit.jupiter:junit-jupiter", version.ref = "jupiter" }
jupiter-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "jupiter" }
jupiter-platform-testkit = { module = "org.junit.platform:junit-platform-testkit", version.ref = "jupiterPlatform" }
jupiter-platform-reporting = { module = "org.junit.platform:junit-platform-reporting", version.ref = "jupiterPlatform" }

mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }

testng = { module = "org.testng:testng", version.ref = "testNg" }

cucumber-java = { module = "io.cucumber:cucumber-java", version.ref = "cucumber" }
cucumber-junit = { module = "io.cucumber:cucumber-junit", version.ref = "cucumber" }
cucumber-spring = { module = "io.cucumber:cucumber-spring", version.ref = "cucumber" }

[bundles]
spring-boot-report = ["spring-boot-starter", "spring-boot-starter-json", "spring-boot-starter-thymeleaf"]
spring-web = ["spring-core", "spring-context", "spring-web"]
spring-test = ["spring-core", "spring-context", "spring-test"]
logback = ["logback-classic", "logback-core"]

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBootPlugin" }
lombok = { id = "io.freefair.lombok", version.ref = "lombokPlugin" }
minify = { id = "org.gradlewebtools.minify", version.ref = "minifyPlugin" }
versioner = { id = "io.toolebox.git-versioner", version.ref = "gitVersionerPlugin" }
index-scan = { id = "org.sonatype.gradle.plugins.scan", version.ref = "indexScanPlugin" }
owasp-dependencycheck = { id = "org.owasp.dependencycheck", version.ref = "owaspPlugin" }
