name: "DependencyCheck"

on:
  push:
    branches: ["main"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]
    paths:
      - "gradle/**"
      - ".release-trigger"
      - ".snyk"
      - ".github/workflows/gradle-dependency-check.yml"
      - "mission-report/flight-evaluation-report/node/package.json"
      - "mission-report/flight-evaluation-report/node/package-lock.json"
  workflow_dispatch:
  schedule:
    # * is a special character in YAML, so we have to quote this string
    - cron: "0 7 * * 1,3,5"

permissions: read-all

jobs:
  security:
    permissions:
      # required for all workflows
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle@9adf32b1121593767fc3c057af55b55db032dc04 # v1.0.0
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: >
            --fail-on=all
            --all-projects
            --show-vulnerable-paths=all
            --configuration-matching="^runtimeClasspath|compileClassPath|testRuntimeClasspath|testCompileClassPath$" 
            --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@99df26d4f13ea111d4ec1a7dddef6063f76b97e9 # v4.37.0
        with:
          sarif_file: snyk.sarif


