name: CreateRelease
on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Draft release action
    runs-on: ubuntu-latest
    steps:
      - name: Create PR
        uses: actions/github-script@85e88a66eaa831097093a3d278536947f2984d20 # v4.0.1
        with:
          script: |
            github.rest.repos.createRelease({
              owner: "${{ github.repository_owner }}",
              repo: "abort-mission",
              tag_name: "${{ github.ref_name }}",
              generate_release_notes: true,
              draft: true
            });
